spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  health:
    redis:
      enabled: false
