drop:
  - changed-files:
      - any-glob-to-any-file: services/drop-service/**

eureka:
  - changed-files:
      - any-glob-to-any-file: services/eureka-server/**

config:
  - changed-files:
      - any-glob-to-any-file: services/config-server/**

gateway:
  - changed-files:
      - any-glob-to-any-file: services/gateway/**

notification:
  - changed-files:
      - any-glob-to-any-file: services/notification-service/**

order:
  - changed-files:
      - any-glob-to-any-file: services/order-service/**

payment:
  - changed-files:
      - any-glob-to-any-file: services/payment-service/**

product:
  - changed-files:
      - any-glob-to-any-file: services/product-service/**

raffle:
  - changed-files:
      - any-glob-to-any-file: services/raffle-service/**

user:
  - changed-files:
      - any-glob-to-any-file: services/user-service/**

coupon:
  - changed-files:
      - any-glob-to-any-file: services/coupon-service/**

common:
  - changed-files:
      - any-glob-to-any-file: common/**

infra:
  - changed-files:
      - any-glob-to-any-file: infra/**

documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**
      - any-glob-to-any-file: '*.md'

github:
  - changed-files:
      - any-glob-to-any-file: .github/**
