"domain: drop":
  - changed-files:
      - any-glob-to-any-file: services/drop-service/**

"domain: eureka":
  - changed-files:
      - any-glob-to-any-file: services/eureka-server/**

"domain: config":
  - changed-files:
      - any-glob-to-any-file: services/config-server/**

"domain: gateway":
  - changed-files:
      - any-glob-to-any-file: services/gateway/**

"domain: notification":
  - changed-files:
      - any-glob-to-any-file: services/notification-service/**

"domain: order":
  - changed-files:
      - any-glob-to-any-file: services/order-service/**

"domain: payment":
  - changed-files:
      - any-glob-to-any-file: services/payment-service/**

"domain: product":
  - changed-files:
      - any-glob-to-any-file: services/product-service/**

"domain: raffle":
  - changed-files:
      - any-glob-to-any-file: services/raffle-service/**

"domain: user":
  - changed-files:
      - any-glob-to-any-file: services/user-service/**

"domain: coupon":
  - changed-files:
      - any-glob-to-any-file: services/coupon-service/**

"⚙️ common":
  - changed-files:
      - any-glob-to-any-file: common/**

"⚙️ infra":
  - changed-files:
      - any-glob-to-any-file: infra/**

"📝 docs":
  - changed-files:
      - any-glob-to-any-file: docs/**
      - any-glob-to-any-file: '*.md'

"⚙️ github":
  - changed-files:
      - any-glob-to-any-file: .github/**
