rootProject.name = 'OMC'

include 'common'
include 'arch-rules'
include 'services:gateway'
include 'services:eureka-server'
include 'services:config-server'
include 'services:user-service'
include 'services:product-service'
include 'services:drop-service'
include 'services:raffle-service'
include 'services:order-service'
include 'services:payment-service'
include 'services:coupon-service'
include 'services:notification-service'

