eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

gateway:
  secret: ${GATEWAY_SECRET:local-secret}

app:
  swagger:
    server-url: ${SWAGGER_SERVER_URL:http://localhost:8080}
