server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: product-service-admin
          uri: lb://product-service
          predicates:
            - Path=/api/v1/admin/products/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**

        - id: drop-service-admin
          uri: lb://drop-service
          predicates:
            - Path=/api/v1/admin/drops/**

        - id: drop-service
          uri: lb://drop-service
          predicates:
            - Path=/api/v1/drops/**

        - id: raffle-service
          uri: lb://raffle-service
          predicates:
            - Path=/api/v1/raffles/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**

        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/v1/coupons/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8180/realms/omc/protocol/openid-connect/certs}

gateway:
  secret: ${GATEWAY_SECRET:local-secret}

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /v3/api-docs/user-service
      - name: product-service
        url: /v3/api-docs/product-service
      - name: drop-service
        url: /v3/api-docs/drop-service
      - name: order-service
        url: /v3/api-docs/order-service
      - name: payment-service
        url: /v3/api-docs/payment-service
      - name: raffle-service
        url: /v3/api-docs/raffle-service
      - name: coupon-service
        url: /v3/api-docs/coupon-service
      - name: notification-service
        url: /v3/api-docs/notification-service

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
