server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**

        - id: drop-service
          uri: lb://drop-service
          predicates:
            - Path=/api/v1/drops/**

        - id: raffle-service
          uri: lb://raffle-service
          predicates:
            - Path=/api/v1/raffles/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8180/realms/omc/protocol/openid-connect/certs}

gateway:
  secret: ${GATEWAY_SECRET:local-secret}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
