CREATE SCHEMA IF NOT EXISTS user_db;
CREATE SCHEMA IF NOT EXISTS product_db;
CREATE SCHEMA IF NOT EXISTS drop_db;
CREATE SCHEMA IF NOT EXISTS raffle_db;
CREATE SCHEMA IF NOT EXISTS order_db;
CREATE SCHEMA IF NOT EXISTS payment_db;
CREATE SCHEMA IF NOT EXISTS coupon_db;
CREATE SCHEMA IF NOT EXISTS notification_db;
