spring:
  application:
    name: raffle-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://payment-service:8085}
