global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'drop-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['drop-service:8082']

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8083']

  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8084']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8085']

  - job_name: 'raffle-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['raffle-service:8086']

  - job_name: 'coupon-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['coupon-service:8087']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8088']

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8081']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']