dependencies {
    // Swagger
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9'

    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // Spring Cloud OpenFeign 의존성 추가
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    implementation 'org.springframework.boot:spring-boot-starter-security'

    //직렬화, 역직렬화
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}
